<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Asset extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Asset_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','asset/tbl_asset_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Asset_model->json();
    }

    public function read($id) 
    {
        $row = $this->Asset_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_asset' => $row->id_asset,
		'asset' => $row->asset,
		'kode_asset' => $row->kode_asset,
	    );
            $this->template->load('template','asset/tbl_asset_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('asset'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('asset/create_action'),
	    'id_asset' => set_value('id_asset'),
	    'asset' => set_value('asset'),
	    'kode_asset' => set_value('kode_asset'),
	);
        $this->template->load('template','asset/tbl_asset_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'asset' => $this->input->post('asset',TRUE),
		'kode_asset' => $this->input->post('kode_asset',TRUE),
	    );

            $this->Asset_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('asset'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Asset_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('asset/update_action'),
		'id_asset' => set_value('id_asset', $row->id_asset),
		'asset' => set_value('asset', $row->asset),
		'kode_asset' => set_value('kode_asset', $row->kode_asset),
	    );
            $this->template->load('template','asset/tbl_asset_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('asset'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_asset', TRUE));
        } else {
            $data = array(
		'asset' => $this->input->post('asset',TRUE),
		'kode_asset' => $this->input->post('kode_asset',TRUE),
	    );

            $this->Asset_model->update($this->input->post('id_asset', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('asset'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Asset_model->get_by_id($id);

        if ($row) {
            $this->Asset_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('asset'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('asset'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('asset', 'asset', 'trim|required');
	$this->form_validation->set_rules('kode_asset', 'kode asset', 'trim|required');

	$this->form_validation->set_rules('id_asset', 'id_asset', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Asset.php */
/* Location: ./application/controllers/Asset.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-21 16:27:49 */
/* http://harviacode.com */