<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Qr extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Qr_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','qr/tbl_qr_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Qr_model->json();
    }

    public function read($id) 
    {
        $row = $this->Qr_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_qr' => $row->id_qr,
		'qr_id_barang' => $row->qr_id_barang,
		'qr' => $row->qr,
	    );
            $this->template->load('template','qr/tbl_qr_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('qr'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('qr/create_action'),
	    'id_qr' => set_value('id_qr'),
	    'qr_id_barang' => set_value('qr_id_barang'),
	    'qr' => set_value('qr'),
	);
        $this->template->load('template','qr/tbl_qr_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'qr_id_barang' => $this->input->post('qr_id_barang',TRUE),
		'qr' => $this->input->post('qr',TRUE),
	    );

            $this->Qr_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('qr'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Qr_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('qr/update_action'),
		'id_qr' => set_value('id_qr', $row->id_qr),
		'qr_id_barang' => set_value('qr_id_barang', $row->qr_id_barang),
		'qr' => set_value('qr', $row->qr),
	    );
            $this->template->load('template','qr/tbl_qr_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('qr'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_qr', TRUE));
        } else {
            $data = array(
		'qr_id_barang' => $this->input->post('qr_id_barang',TRUE),
		'qr' => $this->input->post('qr',TRUE),
	    );

            $this->Qr_model->update($this->input->post('id_qr', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('qr'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Qr_model->get_by_id($id);

        if ($row) {
            $this->Qr_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('qr'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('qr'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('qr_id_barang', 'qr id barang', 'trim|required');
	$this->form_validation->set_rules('qr', 'qr', 'trim|required');

	$this->form_validation->set_rules('id_qr', 'id_qr', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Qr.php */
/* Location: ./application/controllers/Qr.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-26 03:50:18 */
/* http://harviacode.com */