<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_model extends CI_Model
{

    public $table = 'tbl_barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_barang,group_barang,jenis_barang_kode,merk_barang_kode,type_barang,uraian_barang,barcode_barang,barcode_barang_detail,serial_number,lokasi_barang_simpan,aset_barang,tag_form_pinjam,qr_code');
        $this->datatables->from('tbl_barang');
        $this->datatables->join('tbl_jenis_barang', 'tbl_barang.jenis_barang = tbl_jenis_barang.id_jenis_barang');
        $this->datatables->join('tbl_merk_barang', 'tbl_barang.merk_barang = tbl_merk_barang.id_merk_barang');
        $this->datatables->join('tbl_lokasi_barang', 'tbl_barang.lokasi_barang = tbl_lokasi_barang.id_lokasi_barang');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_barang.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('assets/images/$2'),'<i class="fa fa-qrcode" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('barang/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))
               , 'id_barang,qr_code');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang', $q);
	$this->db->or_like('group_barang', $q);
	$this->db->or_like('jenis_barang', $q);
	$this->db->or_like('merk_barang', $q);
	$this->db->or_like('type_barang', $q);
	$this->db->or_like('uraian_barang', $q);
	$this->db->or_like('barcode_barang', $q);
	$this->db->or_like('barcode_barang_detail', $q);
	$this->db->or_like('serial_number', $q);
	$this->db->or_like('lokasi_barang', $q);
	$this->db->or_like('aset_barang', $q);
	$this->db->or_like('tag_form_pinjam', $q);
    $this->db->or_like('kondisi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
	$this->db->or_like('group_barang', $q);
	$this->db->or_like('jenis_barang', $q);
	$this->db->or_like('merk_barang', $q);
	$this->db->or_like('type_barang', $q);
	$this->db->or_like('uraian_barang', $q);
	$this->db->or_like('barcode_barang', $q);
	$this->db->or_like('barcode_barang_detail', $q);
	$this->db->or_like('serial_number', $q);
	$this->db->or_like('lokasi_barang', $q);
	$this->db->or_like('aset_barang', $q);
	$this->db->or_like('tag_form_pinjam', $q);
    $this->db->or_like('kondisi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-21 18:18:55 */
/* http://harviacode.com */