<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Peminjaman_model extends CI_Model
{

    public $table = 'tbl_peminjaman';
    public $id = 'id_peminjaman';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->db->distinct();
        $this->datatables->select('no_form_peminjaman,nama_lengkap,nama_program,tgl_peminjaman,status_peminjaman');
        $this->db->where('status_peminjaman', 'DIPINJAM');
        //id_peminjaman,,id_form_barang,user_peminjaman,nama_program,tgl_peminjaman,tgl_pengembalian,status_peminjaman
        $this->datatables->from('tbl_peminjaman');
        $this->datatables->join('tbl_karyawan', 'tbl_peminjaman.user_peminjaman = tbl_karyawan.id_karyawan');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_peminjaman.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('peminjaman/pdf/$1'),'<i class="fa fa-file-pdf-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm','target' =>'new'))." 
            ".anchor(site_url('pengembalian/kembali/$1'),'<i class="fa fa-share" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ",'no_form_peminjaman');
        return $this->datatables->generate();
    }


    function json2() {
        $this->db->distinct();
        $this->datatables->select('no_form_peminjaman,nama_lengkap,nama_program,tgl_peminjaman,tgl_pengembalian,status_peminjaman');
        //id_peminjaman,,id_form_barang,user_peminjaman,nama_program,tgl_peminjaman,tgl_pengembalian,status_peminjaman
        $this->datatables->from('tbl_peminjaman');
        $this->datatables->join('tbl_karyawan', 'tbl_peminjaman.user_peminjaman = tbl_karyawan.id_karyawan');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_peminjaman.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('peminjaman/pdf/$1'),'<i class="fa fa-file-pdf-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('pengembalian/kembali/$1'),'<i class="fa fa-share" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ",'no_form_peminjaman');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_peminjaman', $q);
	$this->db->or_like('no_form_peminjaman', $q);
	$this->db->or_like('id_form_barang', $q);
	$this->db->or_like('user_peminjaman', $q);
	$this->db->or_like('nama_program', $q);
	$this->db->or_like('tgl_peminjaman', $q);
	$this->db->or_like('tgl_pengembalian', $q);
	$this->db->or_like('status_peminjaman', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_peminjaman', $q);
	$this->db->or_like('no_form_peminjaman', $q);
	$this->db->or_like('id_form_barang', $q);
	$this->db->or_like('user_peminjaman', $q);
	$this->db->or_like('nama_program', $q);
	$this->db->or_like('tgl_peminjaman', $q);
	$this->db->or_like('tgl_pengembalian', $q);
	$this->db->or_like('status_peminjaman', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Peminjaman_model.php */
/* Location: ./application/models/Peminjaman_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-21 18:19:53 */
/* http://harviacode.com */