<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Qr_model extends CI_Model
{

    public $table = 'tbl_qr';
    public $id = 'id_qr';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_barang,barcode_barang_detail,qr_code');
        $this->datatables->from('tbl_barang');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_qr.field = table2.field');
        $this->datatables->add_column('Qr', '<img height="60" width="60" src="http://localhost/m1tv/assets/images/$1">','qr_code');
        $this->datatables->add_column('action', anchor(site_url('qr/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('qr/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('qr/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_barang');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_qr', $q);
	$this->db->or_like('qr_id_barang', $q);
	$this->db->or_like('qr', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_qr', $q);
	$this->db->or_like('qr_id_barang', $q);
	$this->db->or_like('qr', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Qr_model.php */
/* Location: ./application/models/Qr_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-26 03:50:18 */
/* http://harviacode.com */